apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "library.metadata.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/auth-url: {{ include "library.service.auth" . }}
    nginx.ingress.kubernetes.io/auth-signin: /login
    # No limit.
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  rules:
    {{- $ingress := .Values.global.ingress | default dict }}
    {{ if $ingress.host }}
    - host: {{ $ingress.host }}
      http:  
    {{ else }}
    - http:
    {{ end }}
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ template "library.metadata.name" . }}
                port:
                  number: {{ template "library.service.port" . }}
