{{/*
deployment
*/}}
---
{{ include "library.deployment" . }}
    spec:
      volumes:
        - name: mnesia
          hostPath:
            path: /var/lib/orchest/userdir/.orchest/rabbitmq-mnesia
            type: DirectoryOrCreate                      
      containers:
      - name: rabbitmq-server
        image: rabbitmq:3
        ports:
        - containerPort: {{ include "library.container.port" . }}
        volumeMounts:
         - name: mnesia
           mountPath: /var/lib/rabbitmq/mnesia