{{/*
deployment
*/}}
---
{{ include "library.deployment" . }}
    spec:
      volumes:
        - name: userdir
          persistentVolumeClaim:
            claimName: userdir-pvc
            readOnly: false
      containers:
      - name: file-manager
        image: orchest/file-manager:latest
        {{ if .Values.service.port}}
        ports:
        - containerPort: {{ .Values.service.port }}
        {{ end }}
        volumeMounts:
         - name: userdir
           mountPath: /userdir
        readinessProbe:
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 1
          periodSeconds: 4
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 5