apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: orchest-ctl
    app.kubernetes.io/part-of: orchest
    app.kubernetes.io/release: orchest
  name: orchest-ctl
rules:
  - apiGroups:
      - "*"
    resources:
      - "*"
    verbs:
      - "*"
