{{/*
deployment
*/}}
---
{{ include "library.deployment" . }}
    spec:                   
      containers:
      - name: nginx-proxy
        image: nginx-proxy:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 80