{{/*
deployment
*/}}
---
{{ include "library.deployment" . }}
    spec:
      volumes:
        - name: userdir
          hostPath:
            path: /var/lib/orchest/userdir
            type: DirectoryOrCreate
        - name: config
          hostPath:
            path: /var/lib/orchest/config
            type: DirectoryOrCreate
      containers:
      - name: auth-server
        image: orchest/auth-server:latest
        {{ if .Values.service.port}}
        ports:
        - containerPort: {{ .Values.service.port }}
        {{ end }}
        env:
        - name: "HOST_OS"
          value: "linux"
        - name: "ORCHEST_LOG_LEVEL"
          value: DEBUG  
        - name: "PYTHONUNBUFFERED"
          value: "TRUE"       
        volumeMounts:
         - name: userdir
           mountPath: /userdir
         - name: config
           mountPath: /config
        startupProbe:
          exec:
            command:
              - sh
              - -c
              - "nc -zvw1 orchest-database 5432 &&
                wget -T 1 -t 1 localhost/login/server-config --spider"
          periodSeconds: 1
          successThreshold: 1
          timeoutSeconds: 5
          failureThreshold: 20
        livenessProbe:
          httpGet:
            path: /login/server-config
            port: 80
            scheme: HTTP
          periodSeconds: 10
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 2