{{/*
deployment
*/}}
---
{{ include "library.deployment" . }}
    spec:
      serviceAccountName: {{ template "library.metadata.name" . }}
      containers:
      - name: orchest-controller
        image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ include "library.spec.image.pullPolicy" . }}
        ports:
        - containerPort: 80
        args:
        - --namespace=$NAMESPACE
        {{ if eq .Values.addons.enableArgo "true" }}
        - --enable=argo-workflow
        {{ end }}
        env:
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace        
