{{/*
deployment
*/}}
---
{{ include "library.deployment" . }}
    spec:
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run
            type: Directory
        - name: userdir
          hostPath:
            path: /var/lib/orchest/userdir
            type: DirectoryOrCreate
      serviceAccountName: {{ template "library.metadata.name" . }}      
      containers:
      - name: celery-worker
        image: orchest/celery-worker:latest
        env:
        - name: "MAX_JOB_RUNS_PARALLELISM"
          value: "1"
        - name: "MAX_INTERACTIVE_RUNS_PARALLELISM"
          value: "1"
        - name: "ORCHEST_LOG_LEVEL"
          value: "INFO"
        - name: "ORCHEST_HOST_GID"
          value: "1"
        - name: "ORCHEST_GPU_ENABLED_INSTANCE"
          value: "FALSE"
        volumeMounts:
         - name: dockersock
           mountPath: /var/run
         - name: userdir
           mountPath: /userdir