apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ template "library.metadata.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    nginx.ingress.kubernetes.io/auth-url: {{ include "library.service.auth" . }}
spec:
  rules:
    - host: {{ template "library.ingress.host" . }}
      http:
        paths:
          - path: /orchest-api
            pathType: Prefix
            backend:
              service:
                name: {{ template "library.metadata.name" . }}
                port:
                  number: {{ template "library.service.port" . }}