apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "library.cluster.orchest.imagebuildercache.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.imagebuildercache.storage }}
  storageClassName: {{ include "library.cluster.orchest.filesystem.storageClass" . }}
