{{/*
deployment
*/}}
---
{{ include "library.deployment" . }}
    spec:
      volumes:
        - name: pgdata
          hostPath:
            path: /var/lib/orchest/userdir/.orchest/database/data
            type: DirectoryOrCreate                      
      containers:
      - name: orchest-database
        image: postgres:13.1
        ports:
        - containerPort: 5432
        env:
        - name: "PGDATA"
          value: "/userdir/.orchest/database/data"
        - name: "POSTGRES_HOST_AUTH_METHOD"
          value: "trust"
        volumeMounts:
         - name: pgdata
           mountPath: /userdir/.orchest/database/data           